apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: worldcoin/world-chain-benchmarking
  description: A repository for benchmarking setup for world-chain/reth and other execution clients
  name: world-chain-benchmarking
spec:
  lifecycle: test
  owner: team-crypto
  type: service
