{
 "title": "Execution Payloads Benchmarks Dashboard",
 "time": { "from": "2025-12-15T16:49:47.384Z", "to": "2025-12-15T21:25:56.793Z" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus DS", "query": "prometheus" },
   { "name": "testid", "label": "Test ID", "query": { "query": "label_values(testid)" } },
   { "name": "quantile_stat", "label": "Trend Metrics Query", "query": { "query": "metrics(k6_http_req_duration_)" } },
   { "name": "adhoc_filter", "label": "AdhocFilter" }
  ]
 },
 "panels": [
  {
   "title": "Performance Overview",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (testid) (k6_iteration_duration_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_duration_$quantile_stat - {{testid}}"
    },
    {
     "expr": "sum by (testid) (irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "http_req_s  - {{testid}}"
    },
    {
     "expr": "sum by (testid) (irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_errors  - {{testid}}"
    }
   ]
  },
  { "title": "Performance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Iterations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(testid) (k6_iterations_total{testid=~\"$testid\"})",
     "legendFormat": "{{testid}}"
    }
   ]
  },
  {
   "title": "Blocks per second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "blocks/s" } },
   "targets": [
    {
     "expr": "sum by(testid) (irate(k6_iterations_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "{{testid}}"
    }
   ]
  },
  {
   "title": "HTTP request failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (testid) (k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"})",
     "legendFormat": "{{testid}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "stat",
   "description": "Select a different Stat to change the query",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(testid) ({\"k6_http_req_duration_$quantile_stat\", testid=~\"$testid\", jrpc_method=\"engine_newPayloadV3\"})",
     "legendFormat": "{{testid}}"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (testid) (irate(k6_data_sent_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "data_sent - {{testid}}"
    },
    {
     "expr": "avg by (testid) (irate(k6_data_received_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "data_received - {{testid}}"
    }
   ]
  },
  {
   "title": "Iterations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (testid) (k6_iteration_duration_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "iteration_duration_$quantile_stat - {{testid}}"
    },
    {
     "expr": "avg by (testid) (k6_dropped_iterations_total{testid=~\"$testid\"})",
     "legendFormat": "dropped_iterations - {{testid}}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "HTTP Latency Timings",
   "type": "timeseries",
   "description": "Select a different Stat to change the query\n\n<a href=\"https://k6.io/docs/using-k6/metrics/reference/#http\" target=\"_blank\">HTTP-specific built-in metrics</a>",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (testid, group) (k6_http_req_blocked_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_blocked_$quantile_stat - {{testid}}{{group}}"
    },
    {
     "expr": "avg by (testid, group) (k6_http_req_tls_handshaking_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_tls_handshaking_$quantile_stat - {{testid}}{{group}}"
    },
    {
     "expr": "avg by (testid, group) (k6_http_req_sending_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_sending_$quantile_stat - {{testid}}{{group}}"
    },
    {
     "expr": "avg by (testid, group) (k6_http_req_waiting_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_waiting_$quantile_stat - {{testid}}{{group}}"
    },
    {
     "expr": "avg by (testid, group) (k6_http_req_receiving_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_receiving_$quantile_stat - {{testid}}{{group}}"
    }
   ]
  },
  {
   "title": "HTTP Latency Stats",
   "type": "timeseries",
   "description": "Select a different Stat to change the query",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (testid, group) (k6_http_req_duration_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_duration_$quantile_stat - {{testid}}{{group}}"
    },
    {
     "expr": "avg by (testid, group) (k6_http_req_duration_$quantile_stat{testid=~\"$testid\", expected_response=\"true\"})",
     "legendFormat": "success_http_req_duration_$quantile_stat - {{testid}}{{group}}"
    },
    {
     "expr": "avg by (testid, group) (k6_http_req_duration_$quantile_stat{testid=~\"$testid\", expected_response=\"false\"})",
     "legendFormat": "errors_http_req_duration_$quantile_stat - {{testid}}{{group}}"
    }
   ]
  },
  {
   "title": "Gas Usage per Payload (Improved)",
   "type": "xychart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "k6_expb_slowest_payloads{testid=~\"$testid\"}",
     "legendFormat": "{{testid}}"
    }
   ]
  },
  {
   "title": "Payloads Durations",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "k6_expb_slowest_payloads{testid=~\"$testid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (testid) (irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "http_req_s - {{testid}}"
    },
    {
     "expr": "sum by (testid) (irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_errors - {{testid}}"
    },
    {
     "expr": "sum by (testid) (irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"true\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_success - {{testid}}"
    }
   ]
  },
  {
   "title": "Blocks Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(testid) (irate(k6_iteration_total{testid=~\"$testid\", expected_response=\"true\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_success - {{testid}}"
    }
   ]
  },
  {
   "title": "Requests by URL",
   "type": "table",
   "description": "min/max/p95/p99 depends on the available Quantile Stats",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "k6_http_req_duration_min{testid=~\"$testid\"}",
     "legendFormat": "min"
    },
    {
     "expr": "k6_http_req_duration_max{testid=~\"$testid\"}",
     "legendFormat": "max"
    },
    {
     "expr": "k6_http_req_duration_p95{testid=~\"$testid\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "k6_http_req_duration_p99{testid=~\"$testid\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_http_req_duration_avg{testid=~\"$testid\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "k6_http_req_duration_med{testid=~\"$testid\"}",
     "legendFormat": "med"
    }
   ]
  },
  { "title": "Checks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Checks list",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "round(k6_checks_rate{testid=~\"$testid\"}, 0.1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checks Success Rate (aggregate individual checks)",
   "type": "timeseries",
   "description": "Filter by check name to query a particular check",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "avg by (testid) (round(k6_checks_rate{testid=~\"$testid\"}, 0.1)*100)",
     "legendFormat": "k6_checks_rate - {{testid}}"
    }
   ]
  }
 ]
}